const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

const MOVIES_AND_SERIES = [
  // --- BİLİM KURGU & AKSİYON DÜNYA SİNEMASI ---
  {
    tmdbId: 693134,
    mediaType: "movie",
    title: "Dune: Çöl Gezegeni Bölüm İki",
    originalTitle: "Dune: Part Two",
    overview: "Paul Atreides, ailesini yok eden komploculara karşı intikam arayışındayken Chani ve Fremen'lerle güçlerini birleştirir. Evrenin kaderini belirleyecek savaş başlamak üzeredir.",
    posterPath: "https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s520b2.jpg",
    releaseYear: "2024",
    voteAverage: 8.3,
    genres: "Bilim Kurgu, Macera, Aksiyon",
    duration: 166,
    isFeatured: true,
    videoUrl: "https://player.videasy.net/movie/693134",
    dubUrl: "https://multiembed.mov/?video_id=693134&tmdb=1&audio=tr",
    subUrl: "https://multiembed.mov/?video_id=693134&tmdb=1&sub=Turkish",
  },
  {
    tmdbId: 872585,
    mediaType: "movie",
    title: "Oppenheimer",
    originalTitle: "Oppenheimer",
    overview: "J. Robert Oppenheimer'ın Manhattan Projesi kapsamında ilk nükleer silahları geliştirme sürecini ve sonrasındaki ahlaki ve siyasi hesaplaşmalarını anlatan biyografik başyapıt.",
    posterPath: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg",
    releaseYear: "2023",
    voteAverage: 8.1,
    genres: "Dram, Tarih, Biyografi",
    duration: 180,
    videoUrl: "https://player.videasy.net/movie/872585",
    dubUrl: "https://multiembed.mov/?video_id=872585&tmdb=1&audio=tr",
    subUrl: "https://multiembed.mov/?video_id=872585&tmdb=1&sub=Turkish",
  },
  {
    tmdbId: 157336,
    mediaType: "movie",
    title: "Yıldızlararası (Interstellar)",
    originalTitle: "Interstellar",
    overview: "İnsanlığın Dünya'daki ömrü tükenirken bir grup astronot, yeni bir yaşanabilir gezegen bulabilmek için bir solucan deliğinden geçerek bilinmeyen galaksilere doğru yolculuğa çıkar.",
    posterPath: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
    releaseYear: "2014",
    voteAverage: 8.4,
    genres: "Macera, Dram, Bilim Kurgu",
    duration: 169,
    videoUrl: "https://player.videasy.net/movie/157336",
    dubUrl: "https://multiembed.mov/?video_id=157336&tmdb=1&audio=tr",
    subUrl: "https://multiembed.mov/?video_id=157336&tmdb=1&sub=Turkish",
  },
  {
    tmdbId: 27205,
    mediaType: "movie",
    title: "Başlangıç (Inception)",
    originalTitle: "Inception",
    overview: "Dom Cobb, insanların rüyalarından bilinçaltı sırlarını çalan usta bir hırsızdır. Ona sunulan son ve imkansız görev: bir fikri çalmak değil, zihne yerleştirmektir.",
    posterPath: "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
    releaseYear: "2010",
    voteAverage: 8.4,
    genres: "Aksiyon, Bilim Kurgu, Macera",
    duration: 148,
    videoUrl: "https://player.videasy.net/movie/27205",
    dubUrl: "https://multiembed.mov/?video_id=27205&tmdb=1&audio=tr",
  },
  {
    tmdbId: 155,
    mediaType: "movie",
    title: "Kara Şövalye (The Dark Knight)",
    originalTitle: "The Dark Knight",
    overview: "Batman, Teğmen Gordon ve Bölge Savcısı Harvey Dent, Gotham'daki suça karşı mücadeleyi sürdürürken şehri anarşiye sürükleyen Joker ortaya çıkar.",
    posterPath: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/dqK9Hag1054tghRQSqLSfrkvQnA.jpg",
    releaseYear: "2008",
    voteAverage: 8.5,
    genres: "Dram, Aksiyon, Suç, Gerilim",
    duration: 152,
    videoUrl: "https://player.videasy.net/movie/155",
  },
  {
    tmdbId: 550,
    mediaType: "movie",
    title: "Dövüş Kulübü (Fight Club)",
    originalTitle: "Fight Club",
    overview: "Uykusuzluk çeken sıradan bir büro çalışanı, gizemli sabun satıcısı Tyler Durden ile tanışır ve hayatı radikal bir yeraltı dövüş kulübüyle kökünden değişir.",
    posterPath: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/hZkgoQYus5vegHoetLkCJzb17zJ.jpg",
    releaseYear: "1999",
    voteAverage: 8.4,
    genres: "Dram, Gerilim",
    duration: 139,
    videoUrl: "https://player.videasy.net/movie/550",
  },
  {
    tmdbId: 603,
    mediaType: "movie",
    title: "Matrix (The Matrix)",
    originalTitle: "The Matrix",
    overview: "Bir bilgisayar korsanı olan Neo, yaşadığı gerçekliğin yapay zeka tarafından yönetilen devasa bir simülasyon olduğunu keşfeder ve insanlığı kurtarmak için seçilmiş kişi olur.",
    posterPath: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/7u3fh9nfj9q7Tl59jM3f2T0iL.jpg",
    releaseYear: "1999",
    voteAverage: 8.2,
    genres: "Aksiyon, Bilim Kurgu",
    duration: 136,
    videoUrl: "https://player.videasy.net/movie/603",
  },
  {
    tmdbId: 680,
    mediaType: "movie",
    title: "Ucuz Roman (Pulp Fiction)",
    originalTitle: "Pulp Fiction",
    overview: "Los Angeles yeraltı dünyasında iki kiralık katil, bir boksör, bir gangster ve karısının hayatları birbirine beklenmedik şiddet ve mizah dolu olaylarla bağlanır.",
    posterPath: "https://image.tmdb.org/t/p/w500/d5iIlFnGhFvlVBs0wV6B1gY0N.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    releaseYear: "1994",
    voteAverage: 8.5,
    genres: "Gerilim, Suç",
    duration: 154,
    videoUrl: "https://player.videasy.net/movie/680",
  },
  {
    tmdbId: 278,
    mediaType: "movie",
    title: "Esaretin Bedeli (The Shawshank Redemption)",
    originalTitle: "The Shawshank Redemption",
    overview: "Haksız yere karısını öldürmekten ömür boyu hapse mahkum edilen banker Andy Dufresne, Shawshank hapishanesinde umudu ve dostluğu canlı tutarak özgürlüğüne giden yolu ilmek ilmek örer.",
    posterPath: "https://image.tmdb.org/t/p/w500/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
    releaseYear: "1994",
    voteAverage: 8.7,
    genres: "Dram, Suç",
    duration: 142,
    videoUrl: "https://player.videasy.net/movie/278",
  },
  {
    tmdbId: 238,
    mediaType: "movie",
    title: "Baba (The Godfather)",
    originalTitle: "The Godfather",
    overview: "New York mafya ailesi Corleone'lerin lideri Don Vito Corleone'nin yaşlanmasıyla birlikte küçük oğlu Michael, suç imparatorluğunun başına geçmek zorunda kalır.",
    posterPath: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/tmU7GeKVybMWF92GImsGZDuAhEj.jpg",
    releaseYear: "1972",
    voteAverage: 8.7,
    genres: "Dram, Suç",
    duration: 175,
    videoUrl: "https://player.videasy.net/movie/238",
  },
  {
    tmdbId: 120,
    mediaType: "movie",
    title: "Yüzüklerin Efendisi: Yüzük Kardeşliği",
    originalTitle: "The Lord of the Rings: The Fellowship of the Ring",
    overview: "Orta Dünya'yı karanlığa boğacak Tek Yüzük'ü yok etmek için Hobbit Frodo Baggins ve yoldaşları Mordor'a doğru tehlikeli bir yolculuğa çıkar.",
    posterPath: "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/vRQnzOn4H1vt6irSafMMxeJ0TMm.jpg",
    releaseYear: "2001",
    voteAverage: 8.4,
    genres: "Macera, Fantezi, Aksiyon",
    duration: 178,
    videoUrl: "https://player.videasy.net/movie/120",
  },
  {
    tmdbId: 122,
    mediaType: "movie",
    title: "Yüzüklerin Efendisi: Kralın Dönüşü",
    originalTitle: "The Lord of the Rings: The Return of the King",
    overview: "Gondor'un kaderini belirleyecek büyük savaş başlarken Frodo ve Sam, Hüküm Dağı'nın derinliklerine doğru ilerler.",
    posterPath: "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg",
    releaseYear: "2003",
    voteAverage: 8.6,
    genres: "Macera, Fantezi, Aksiyon",
    duration: 201,
    videoUrl: "https://player.videasy.net/movie/122",
  },
  {
    tmdbId: 603692,
    mediaType: "movie",
    title: "John Wick: Bölüm 4",
    originalTitle: "John Wick: Chapter 4",
    overview: "John Wick, Yüksek Şura'ya karşı özgürlüğünü kazanmak için dünyanın en güçlü yer altı liderleriyle yüzleşmek zorundadır.",
    posterPath: "https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/h8gHn0OzBoaefW7At1R5JOWTIFG.jpg",
    releaseYear: "2023",
    voteAverage: 7.7,
    genres: "Aksiyon, Gerilim, Suç",
    duration: 169,
    videoUrl: "https://player.videasy.net/movie/603692",
  },
  {
    tmdbId: 414906,
    mediaType: "movie",
    title: "The Batman",
    originalTitle: "The Batman",
    overview: "Gotham Şehri'nin yozlaşmış seçkinlerini hedef alan sadist bir seri katil olan Riddler'ın peşine düşen Bruce Wayne, şehrin karanlık sırlarıyla yüzleşir.",
    posterPath: "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg",
    releaseYear: "2022",
    voteAverage: 7.7,
    genres: "Suç, Gizem, Gerilim",
    duration: 176,
    videoUrl: "https://player.videasy.net/movie/414906",
  },
  {
    tmdbId: 475557,
    mediaType: "movie",
    title: "Joker",
    originalTitle: "Joker",
    overview: "Toplum tarafından dışlanan ve akıl sağlığı bozulan başarısız komedyen Arthur Fleck, Gotham şehrini kaosa sürükleyen ikonik suç dehasına dönüşür.",
    posterPath: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg",
    releaseYear: "2019",
    voteAverage: 8.2,
    genres: "Suç, Gerilim, Dram",
    duration: 122,
    videoUrl: "https://player.videasy.net/movie/475557",
  },
  {
    tmdbId: 98,
    mediaType: "movie",
    title: "Gladyatör (Gladiator)",
    originalTitle: "Gladiator",
    overview: "İhanete uğrayan ve ailesi katledilen Romalı General Maximus, intikam almak için Kolezyum'da bir gladyatör olarak yükselir.",
    posterPath: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/Ar7ocvB9v2d1M0U6fO6J1Lq4YkF.jpg",
    releaseYear: "2000",
    voteAverage: 8.2,
    genres: "Aksiyon, Dram, Macera",
    duration: 155,
    videoUrl: "https://player.videasy.net/movie/98",
  },

  // --- POPÜLER YABANCI DİZİLER ---
  {
    tmdbId: 1396,
    mediaType: "tv",
    title: "Breaking Bad",
    originalTitle: "Breaking Bad",
    overview: "Kanser teşhisi konan bir lise kimya öğretmeni olan Walter White, ailesinin geleceğini garanti altına almak için eski bir öğrencisiyle birlikte metamfetamin üretimine başlar.",
    posterPath: "https://image.tmdb.org/t/p/w500/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg",
    releaseYear: "2008",
    voteAverage: 8.9,
    genres: "Dram, Suç",
    seasonsCount: 5,
    episodesCount: 62,
    isFeatured: true,
    videoUrl: "https://player.videasy.net/tv/1396/1/1",
    dubUrl: "https://multiembed.mov/?video_id=1396&tmdb=1&s=1&e=1&audio=tr",
    subUrl: "https://multiembed.mov/?video_id=1396&tmdb=1&s=1&e=1&sub=Turkish",
  },
  {
    tmdbId: 94605,
    mediaType: "tv",
    title: "Arcane",
    originalTitle: "Arcane",
    overview: "Piltover'ın ütopik şehri ile Zaun'un baskı altındaki yeraltı dünyası arasındaki sert çatışmada iki ikonik League of Legends şampiyonu karşı karşıya gelir.",
    posterPath: "https://image.tmdb.org/t/p/w500/fqldf2t8ztc9aiwn397rHgYeRao.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/2ombOoJYJUmnvdLz4n0zM572s6y.jpg",
    releaseYear: "2021",
    voteAverage: 8.7,
    genres: "Animasyon, Bilim Kurgu, Aksiyon, Macera",
    seasonsCount: 2,
    episodesCount: 18,
    videoUrl: "https://player.videasy.net/tv/94605/1/1",
  },
  {
    tmdbId: 66732,
    mediaType: "tv",
    title: "Stranger Things",
    originalTitle: "Stranger Things",
    overview: "Küçük bir kasabada genç bir çocuk kaybolduğunda, gizli deneyler, doğaüstü güçler ve tuhaf küçük bir kızla dolu gizemli bir dünya gün yüzüne çıkar.",
    posterPath: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
    releaseYear: "2016",
    voteAverage: 8.6,
    genres: "Bilim Kurgu, Dram, Gizem",
    seasonsCount: 4,
    episodesCount: 34,
    videoUrl: "https://player.videasy.net/tv/66732/1/1",
  },
  {
    tmdbId: 1399,
    mediaType: "tv",
    title: "Taht Oyunları (Game of Thrones)",
    originalTitle: "Game of Thrones",
    overview: "Westeros'un Yedi Krallığı'nda soylu aileler Demir Taht'ı ele geçirmek için ölümcül entrikalar ve savaşlar yürütürken kuzeyden kadim bir tehdit yaklaşır.",
    posterPath: "https://image.tmdb.org/t/p/w500/7WUhnWGx5OOt4ljR0ZmBg3Q0ngn.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg",
    releaseYear: "2011",
    voteAverage: 8.4,
    genres: "Dram, Fantezi, Macera",
    seasonsCount: 8,
    episodesCount: 73,
    videoUrl: "https://player.videasy.net/tv/1399/1/1",
  },
  {
    tmdbId: 100088,
    mediaType: "tv",
    title: "The Last of Us",
    originalTitle: "The Last of Us",
    overview: "Medeniyetin ölümcül bir mantar salgınıyla yok olmasının ardından, sertleşmiş bir hayatta kalan olan Joel, insanlığın son umudu olabilecek 14 yaşındaki Ellie'yi korumak için yola çıkar.",
    posterPath: "https://image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqAt2V7JMrRI.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg",
    releaseYear: "2023",
    voteAverage: 8.6,
    genres: "Dram, Macera, Bilim Kurgu",
    seasonsCount: 1,
    episodesCount: 9,
    videoUrl: "https://player.videasy.net/tv/100088/1/1",
  },
  {
    tmdbId: 76479,
    mediaType: "tv",
    title: "The Boys",
    originalTitle: "The Boys",
    overview: "Güçlerini ve şöhretlerini kötüye kullanan yozlaşmış süper kahramanları alaşağı etmek için bir araya gelen bir grup intikamcı sıradan insanın kanlı mücadelesi.",
    posterPath: "https://image.tmdb.org/t/p/w500/7Ns6tO3aYjppI5LoNOi397SC347.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg",
    releaseYear: "2019",
    voteAverage: 8.5,
    genres: "Bilim Kurgu, Aksiyon, Komedi",
    seasonsCount: 4,
    episodesCount: 32,
    videoUrl: "https://player.videasy.net/tv/76479/1/1",
  },
  {
    tmdbId: 60059,
    mediaType: "tv",
    title: "Better Call Saul",
    originalTitle: "Better Call Saul",
    overview: "Küçük çaplı avukat Jimmy McGill'in ahlaki sınırları aşarak suç dünyasının kurnaz avukatı Saul Goodman'a dönüşüm hikayesi.",
    posterPath: "https://image.tmdb.org/t/p/w500/fC2HDm5t0kHsf79dSZQH7QCJDCv.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/r0Q6vd9AyHJ5YQG48T6Eg93WPaE.jpg",
    releaseYear: "2015",
    voteAverage: 8.7,
    genres: "Dram, Suç",
    seasonsCount: 6,
    episodesCount: 63,
    videoUrl: "https://player.videasy.net/tv/60059/1/1",
  },
  {
    tmdbId: 87108,
    mediaType: "tv",
    title: "Chernobyl",
    originalTitle: "Chernobyl",
    overview: "Nisan 1986'da Sovyet Ukrayna'sında meydana gelen Çernobil Nükleer Santrali felaketinin ardındaki insan hikayelerini, fedakarlıkları ve örtbas çabalarını anlatan mini dizi.",
    posterPath: "https://image.tmdb.org/t/p/w500/hlLXt2tOPT6RRnjiUmoxyG9LTFi.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/uL6Ad12W0m6v2d1rPzT9c1T7v0f.jpg",
    releaseYear: "2019",
    voteAverage: 8.7,
    genres: "Dram, Tarih",
    seasonsCount: 1,
    episodesCount: 5,
    videoUrl: "https://player.videasy.net/tv/87108/1/1",
  },

  // --- TÜRK SİNEMASI & DİZİLERİ (KÜLT VE POPÜLER YAPIMLAR) ---
  {
    tmdbId: 9381,
    mediaType: "movie",
    title: "G.O.R.A.",
    originalTitle: "G.O.R.A.",
    overview: "Halı tüccarı Arif, uzaylılar tarafından kaçırılıp G.O.R.A. gezegenine götürülür. Orada prenses Ceku'ya aşık olur ve zalim Komutan Logar'a karşı destansı bir kaçış planı kurar.",
    posterPath: "https://image.tmdb.org/t/p/w500/6yqG2J3Z1D5M6K9H1I3N5Z9M6P.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/9i3N5Z9M6P6yqG2J3Z1D5M6K9H1.jpg",
    releaseYear: "2004",
    voteAverage: 8.0,
    genres: "Komedi, Bilim Kurgu, Macera",
    duration: 127,
    videoUrl: "https://player.videasy.net/movie/9381",
  },
  {
    tmdbId: 21634,
    mediaType: "movie",
    title: "A.R.O.G.",
    originalTitle: "A.R.O.G.",
    overview: "Komutan Logar tarafından taş devrine yollanan Arif, prehistorik insanlara uygarlık öğretirken dinozorlarla ve rakip kabilelerle mücadele eder.",
    posterPath: "https://image.tmdb.org/t/p/w500/6v0m0mQzU9F7r1t9jQ7j0v0.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/6v0m0mQzU9F7r1t9jQ7j0v0.jpg",
    releaseYear: "2008",
    voteAverage: 7.4,
    genres: "Komedi, Bilim Kurgu, Fantezi",
    duration: 129,
    videoUrl: "https://player.videasy.net/movie/21634",
  },
  {
    tmdbId: 10681,
    mediaType: "movie",
    title: "Vizontele",
    originalTitle: "Vizontele",
    overview: "1974 yılında Van'ın küçük bir kasabasına ilk kez televizyon gelir. Belediye Başkanı Nazmi Bey ve kasabanın deli-dahi genci Emin, bu sihirli kutuyu çalıştırmak için uğraşır.",
    posterPath: "https://image.tmdb.org/t/p/w500/y6wG2J3Z1D5M6K9H1I3N5Z9M6P.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/y6wG2J3Z1D5M6K9H1I3N5Z9M6P.jpg",
    releaseYear: "2001",
    voteAverage: 8.0,
    genres: "Komedi, Dram",
    duration: 110,
    videoUrl: "https://player.videasy.net/movie/10681",
  },
  {
    tmdbId: 260346,
    mediaType: "movie",
    title: "Kış Uykusu (Winter Sleep)",
    originalTitle: "Kış Uykusu",
    overview: "Nuri Bilge Ceylan'ın Cannes'da Altın Palmiye kazanan başyapıtı. Emekli bir tiyatro oyuncusu olan Aydın, Kapadokya'daki otelinde genç karısı ve kız kardeşiyle birlikte kışın yalnızlığında ahlaki ve insani hesaplaşmalar yaşar.",
    posterPath: "https://image.tmdb.org/t/p/w500/qjY7p3M1K0J3r1t9jQ7j0v0.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/qjY7p3M1K0J3r1t9jQ7j0v0.jpg",
    releaseYear: "2014",
    voteAverage: 8.1,
    genres: "Dram",
    duration: 196,
    videoUrl: "https://player.videasy.net/movie/260346",
  },
  {
    tmdbId: 109962,
    mediaType: "movie",
    title: "Bir Zamanlar Anadolu'da",
    originalTitle: "Bir Zamanlar Anadolu'da",
    overview: "Bir savcı, bir doktor ve bir cinayet zanlısı, Anadolu bozkırının karanlığında bir ceset aramak için saatler süren kasvetli ve felsefi bir yolculuğa çıkar.",
    posterPath: "https://image.tmdb.org/t/p/w500/a9K0J3r1t9jQ7j0v0m0mQzU9F7r.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/a9K0J3r1t9jQ7j0v0m0mQzU9F7r.jpg",
    releaseYear: "2011",
    voteAverage: 7.9,
    genres: "Dram, Suç",
    duration: 157,
    videoUrl: "https://player.videasy.net/movie/109962",
  },
  {
    tmdbId: 30983,
    mediaType: "tv",
    title: "Ezel",
    originalTitle: "Ezel",
    overview: "En yakın dostları ve sevdiği kadın tarafından kurulan bir kumpasla hapse atılan Ömer, cezaevinde Ramiz Dayı'dan hayat dersleri alarak estetik ameliyatla Ezel olarak geri döner ve intikam savaşını başlatır.",
    posterPath: "https://image.tmdb.org/t/p/w500/jL5M6K9H1I3N5Z9M6P6yqG2J3Z1.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/jL5M6K9H1I3N5Z9M6P6yqG2J3Z1.jpg",
    releaseYear: "2009",
    voteAverage: 8.8,
    genres: "Dram, Suç, Aksiyon",
    seasonsCount: 2,
    episodesCount: 71,
    isFeatured: true,
    videoUrl: "https://player.videasy.net/tv/30983/1/1",
  },
  {
    tmdbId: 44264,
    mediaType: "tv",
    title: "Behzat Ç. Bir Ankara Polisiyesi",
    originalTitle: "Behzat Ç.",
    overview: "Ankara Emniyet Müdürlüğü Cinayet Büro Amiri Behzat Ç. ve ekibi, başkentin karanlık sokaklarındaki cinayetleri çözerken bürokrasi ve derin güçlerle çatışır.",
    posterPath: "https://image.tmdb.org/t/p/w500/kK9H1I3N5Z9M6P6yqG2J3Z1D5M6.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/kK9H1I3N5Z9M6P6yqG2J3Z1D5M6.jpg",
    releaseYear: "2010",
    voteAverage: 8.7,
    genres: "Dram, Suç, Gizem",
    seasonsCount: 4,
    episodesCount: 105,
    videoUrl: "https://player.videasy.net/tv/44264/1/1",
  },
  {
    tmdbId: 119864,
    mediaType: "tv",
    title: "Gibi",
    originalTitle: "Gibi",
    overview: "Yılmaz, İlkkan ve Ersoy'un sıradan görünen hayatlarında başlarına gelen absürt, trajikomik ve felsefi olaylar silsilesi.",
    posterPath: "https://image.tmdb.org/t/p/w500/mI3N5Z9M6P6yqG2J3Z1D5M6K9H1.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/mI3N5Z9M6P6yqG2J3Z1D5M6K9H1.jpg",
    releaseYear: "2021",
    voteAverage: 8.9,
    genres: "Komedi",
    seasonsCount: 5,
    episodesCount: 55,
    videoUrl: "https://player.videasy.net/tv/119864/1/1",
  },
];

async function main() {
  console.log("Katalog içerikleri veritabanına aktarılıyor...");

  let addedCount = 0;
  for (const item of MOVIES_AND_SERIES) {
    await prisma.mediaItem.upsert({
      where: { tmdbId: item.tmdbId },
      update: item,
      create: item,
    });
    addedCount++;
  }

  console.log(`Başarılı! Toplam ${addedCount} adet zengin film ve dizi kataloğu veritabanına eklendi.`);
}

main()
  .catch((e) => console.error(e))
  .finally(() => prisma.$disconnect());
