const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

const MORE_MOVIES = [
  {
    tmdbId: 769,
    mediaType: "movie",
    title: "Sıkı Dostlar (Goodfellas)",
    overview: "Henry Hill ve mafya arkadaşlarının 30 yıllık yükseliş ve çöküş öyküsü.",
    posterPath: "https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
    releaseYear: "1990",
    voteAverage: 8.5,
    genres: "Dram, Suç",
    duration: 145,
    videoUrl: "https://player.videasy.net/movie/769",
  },
  {
    tmdbId: 274,
    mediaType: "movie",
    title: "Kuzuların Sessizliği (The Silence of the Lambs)",
    overview: "Genç FBI ajanı Clarice Starling, seri katil Buffalo Bill'i yakalamak için zeki yamyam Dr. Hannibal Lecter'ın yardımına başvurur.",
    posterPath: "https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg",
    releaseYear: "1991",
    voteAverage: 8.3,
    genres: "Suç, Dram, Gerilim",
    duration: 118,
    videoUrl: "https://player.videasy.net/movie/274",
  },
  {
    tmdbId: 857,
    mediaType: "movie",
    title: "Er Ryan'ı Kurtarmak (Saving Private Ryan)",
    overview: "Normandiya çıkarmasından sonra bir grup Amerikan askeri, kardeşleri savaşta ölen Er Ryan'ı bulup eve getirmek için düşman hatlarının gerisine sızar.",
    posterPath: "https://image.tmdb.org/t/p/w500/uqx37cS8cpHg8x35f9U5IBlrE65.jpg",
    releaseYear: "1998",
    voteAverage: 8.2,
    genres: "Dram, Tarih, Savaş",
    duration: 169,
    videoUrl: "https://player.videasy.net/movie/857",
  },
  {
    tmdbId: 497,
    mediaType: "movie",
    title: "Yeşil Yol (The Green Mile)",
    overview: "Ölüm koridorunda gardiyan olan Paul Edgecomb, doğaüstü iyileştirme gücüne sahip devasa siyahi mahkum John Coffey ile tanışır.",
    posterPath: "https://image.tmdb.org/t/p/w500/velWPhVMQeQKcxggNEU8YmIo52R.jpg",
    releaseYear: "1999",
    voteAverage: 8.5,
    genres: "Fantezi, Dram, Suç",
    duration: 189,
    videoUrl: "https://player.videasy.net/movie/497",
  },
  {
    tmdbId: 105,
    mediaType: "movie",
    title: "Geleceğe Dönüş (Back to the Future)",
    overview: "Marty McFly, çılgın bilim insanı Doc Brown'ın icat ettiği DeLorean zaman makinesiyle yanlışlıkla 1955 yılına gider.",
    posterPath: "https://image.tmdb.org/t/p/w500/fNOH9f1aA7XRTzl1sAOx9iF553Q.jpg",
    releaseYear: "1985",
    voteAverage: 8.3,
    genres: "Macera, Komedi, Bilim Kurgu",
    duration: 116,
    videoUrl: "https://player.videasy.net/movie/105",
  },
  {
    tmdbId: 807,
    mediaType: "movie",
    title: "Yedi (Se7en)",
    overview: "Emekliliği yaklaşan tecrübeli bir dedektif ile yeni atanan genç ortağı, yedi ölümcül günahı işleyen bir seri katilin peşine düşer.",
    posterPath: "https://image.tmdb.org/t/p/w500/6yoghtyTBoPvxDuDX8IUHG9Rh5P.jpg",
    releaseYear: "1995",
    voteAverage: 8.4,
    genres: "Suç, Gizem, Gerilim",
    duration: 127,
    videoUrl: "https://player.videasy.net/movie/807",
  },
  {
    tmdbId: 101,
    mediaType: "movie",
    title: "Leon: Sevginin Gücü (Léon: The Professional)",
    overview: "Ailesi yozlaşmış bir DEA ajanı tarafından katledilen 12 yaşındaki Mathilda, kiralık katil Leon'a sığınır ve intikam almayı öğrenir.",
    posterPath: "https://image.tmdb.org/t/p/w500/yI6X2cQ9zg9YgXgL2g9e3X2e4Y.jpg",
    releaseYear: "1994",
    voteAverage: 8.3,
    genres: "Suç, Dram, Aksiyon",
    duration: 110,
    videoUrl: "https://player.videasy.net/movie/101",
  },
  {
    tmdbId: 280,
    mediaType: "movie",
    title: "Terminatör 2: Mahşer Günü",
    originalTitle: "Terminator 2: Judgment Day",
    overview: "Gelecekteki insan direnişinin lideri John Connor'ı korumak için yeniden programlanmış bir T-800, ölümcül T-1000'e karşı savaşır.",
    posterPath: "https://image.tmdb.org/t/p/w500/weVXMD5QBGeQil4HEATZqAkXeEc.jpg",
    releaseYear: "1991",
    voteAverage: 8.1,
    genres: "Aksiyon, Bilim Kurgu",
    duration: 137,
    videoUrl: "https://player.videasy.net/movie/280",
  },
  {
    tmdbId: 377,
    mediaType: "movie",
    title: "Yaratık (Alien)",
    overview: "Ticari bir kargo gemisinin mürettebatı, terk edilmiş bir uzay aracında ölümcül ve mükemmel bir uzaylı yaratıkla mahsur kalır.",
    posterPath: "https://image.tmdb.org/t/p/w500/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg",
    releaseYear: "1979",
    voteAverage: 8.2,
    genres: "Korku, Bilim Kurgu",
    duration: 117,
    videoUrl: "https://player.videasy.net/movie/377",
  },
  {
    tmdbId: 111,
    mediaType: "movie",
    title: "Yaralı Yüz (Scarface)",
    overview: "Kübalı mülteci Tony Montana, 1980'ler Miami'sinde uyuşturucu imparatoru olmak için acımasızca yükselir.",
    posterPath: "https://image.tmdb.org/t/p/w500/iQ5z9Tugv89S0e4pL0m1uN2b4F.jpg",
    releaseYear: "1983",
    voteAverage: 8.2,
    genres: "Aksiyon, Suç, Dram",
    duration: 170,
    videoUrl: "https://player.videasy.net/movie/111",
  },
  {
    tmdbId: 103,
    mediaType: "movie",
    title: "Taksi Şoförü (Taxi Driver)",
    overview: "Vietnam gazisi Travis Bickle, New York gecelerinde taksi şoförlüğü yaparken şehrin yozlaşmışlığına karşı şiddet dolu bir adalet arayışına girer.",
    posterPath: "https://image.tmdb.org/t/p/w500/ekstpH69PgWZJuG81iwRIbt7IM.jpg",
    releaseYear: "1976",
    voteAverage: 8.2,
    genres: "Suç, Dram",
    duration: 114,
    videoUrl: "https://player.videasy.net/movie/103",
  },
  {
    tmdbId: 694,
    mediaType: "movie",
    title: "Cinnet (The Shining)",
    overview: "Kışın kapalı olan bir otele bekçi olarak ailesiyle taşınan yazar Jack Torrance, otelin kötücül güçleri tarafından yavaş yavaş deliliğe sürüklenir.",
    posterPath: "https://image.tmdb.org/t/p/w500/xazWoLealQwEgqZ89AcZKlB9RkW.jpg",
    releaseYear: "1980",
    voteAverage: 8.2,
    genres: "Korku, Gerilim",
    duration: 146,
    videoUrl: "https://player.videasy.net/movie/694",
  },
  {
    tmdbId: 500,
    mediaType: "movie",
    title: "Rezervuar Köpekleri (Reservoir Dogs)",
    overview: "Planlanan bir elmas soygununun polisin pusu kurmasıyla faciaya dönüşmesinin ardından hayatta kalan suçlular aralarındaki haini bulmaya çalışır.",
    posterPath: "https://image.tmdb.org/t/p/w500/xi8Iu6qyTfyZVDAh6ta1QVR222V.jpg",
    releaseYear: "1992",
    voteAverage: 8.1,
    genres: "Suç, Gerilim",
    duration: 99,
    videoUrl: "https://player.videasy.net/movie/500",
  },
  {
    tmdbId: 106646,
    mediaType: "movie",
    title: "Para Avcısı (The Wolf of Wall Street)",
    overview: "Jordan Belfort'un Wall Street'te sıfırdan kurduğu milyon dolarlık yozlaşmış borsa krallığı, uyuşturucu ve lüks dolu çöküşü.",
    posterPath: "https://image.tmdb.org/t/p/w500/kWnF3lKk8qH5Q0O0Q9v0U1L2M.jpg",
    releaseYear: "2013",
    voteAverage: 8.0,
    genres: "Biyografi, Komedi, Suç",
    duration: 180,
    videoUrl: "https://player.videasy.net/movie/106646",
  },
  {
    tmdbId: 1422,
    mediaType: "movie",
    title: "Köstebek (The Departed)",
    overview: "Boston polisine sızan bir mafya köstebeği ile mafyanın içine sızan bir gizli polisin hayatta kalma ve birbirini deşifre etme savaşı.",
    posterPath: "https://image.tmdb.org/t/p/w500/nT97ifVT2J1yMQmeq20Qblg61T.jpg",
    releaseYear: "2006",
    voteAverage: 8.2,
    genres: "Dram, Gerilim, Suç",
    duration: 151,
    videoUrl: "https://player.videasy.net/movie/1422",
  },
  {
    tmdbId: 808,
    mediaType: "movie",
    title: "Shrek",
    overview: "Kendi bataklığında huzurla yaşayan yeşil bir dev olan Shrek, evini geri almak için geveze bir eşekle birlikte güzeller güzeli Prenses Fiona'yı kurtarmaya gider.",
    posterPath: "https://image.tmdb.org/t/p/w500/iB64vpL3dIObOtMZg3vUV5Ge4q7.jpg",
    releaseYear: "2001",
    voteAverage: 7.7,
    genres: "Animasyon, Komedi, Fantezi",
    duration: 90,
    videoUrl: "https://player.videasy.net/movie/808",
  },
  {
    tmdbId: 585,
    mediaType: "movie",
    title: "Canavarlar Şirketi (Monsters, Inc.)",
    overview: "Çocukların çığlıklarıyla enerji üreten canavarlar dünyasında Sulley ve Mike, yanlışlıkla dünyalarına giren insan bir bebekle dost olur.",
    posterPath: "https://image.tmdb.org/t/p/w500/wFS0qB46eLw5Z0aYn8v5e5u0M.jpg",
    releaseYear: "2001",
    voteAverage: 7.8,
    genres: "Animasyon, Komedi, Aile",
    duration: 92,
    videoUrl: "https://player.videasy.net/movie/585",
  },
  {
    tmdbId: 12,
    mediaType: "movie",
    title: "Kayıp Balık Nemo (Finding Nemo)",
    overview: "Akvaryuma hapsedilen oğlu Nemo'yu kurtarmak için okyanusun derinliklerine dalan palyaço balığı Marlin ve unutkan Dory'nin macerası.",
    posterPath: "https://image.tmdb.org/t/p/w500/eHuGQ10GzKWFACcuAhSoZeL3nn5.jpg",
    releaseYear: "2003",
    voteAverage: 7.8,
    genres: "Animasyon, Aile",
    duration: 100,
    videoUrl: "https://player.videasy.net/movie/12",
  },
  {
    tmdbId: 10682,
    mediaType: "movie",
    title: "Vizontele Tuuba",
    overview: "1980 darbesi öncesinde Van'ın kasabasına kütüphane müdürü ve tekerlekli sandalyedeki kızı Tuuba'nın gelişiyle yaşanan dokunaklı değişim.",
    posterPath: "https://image.tmdb.org/t/p/w500/y6wG2J3Z1D5M6K9H1I3N5Z9M6P.jpg",
    releaseYear: "2004",
    voteAverage: 7.7,
    genres: "Komedi, Dram",
    duration: 111,
    videoUrl: "https://player.videasy.net/movie/10682",
  },
  {
    tmdbId: 77338,
    mediaType: "movie",
    title: "Pek Yakında",
    overview: "Korsan DVD'ci Zafer'in karısını geri kazanmak için eski sinemacı dostlarıyla birlikte sıfır bütçeli bir film çekme macerası.",
    posterPath: "https://image.tmdb.org/t/p/w500/6v0m0mQzU9F7r1t9jQ7j0v0.jpg",
    releaseYear: "2014",
    voteAverage: 7.3,
    genres: "Komedi, Dram",
    duration: 120,
    videoUrl: "https://player.videasy.net/movie/77338",
  },
];

async function main() {
  console.log("Ek filmler veritabanına ekleniyor...");
  let count = 0;
  for (const item of MORE_MOVIES) {
    await prisma.mediaItem.upsert({
      where: { tmdbId: item.tmdbId },
      update: item,
      create: item,
    });
    count++;
  }
  const totalInDb = await prisma.mediaItem.count();
  console.log(`Tamamlandı! ${count} film daha eklendi. Veritabanındaki TOPLAM film & dizi sayısı: ${totalInDb}`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
