const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

const LARGE_LIBRARY = [
  // --- AKSİYON & BİLİM KURGU ---
  {
    tmdbId: 693134,
    mediaType: "movie",
    title: "Dune: Çöl Gezegeni Bölüm İki",
    originalTitle: "Dune: Part Two",
    overview: "Paul Atreides, ailesini yok eden komploculara karşı intikam arayışındayken Chani ve Fremen'lerle güçlerini birleştirir.",
    posterPath: "https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s520b2.jpg",
    releaseYear: "2024",
    voteAverage: 8.3,
    genres: "Bilim Kurgu, Macera, Aksiyon",
    duration: 166,
    isFeatured: true,
    videoUrl: "https://player.videasy.net/movie/693134",
    dubUrl: "https://multiembed.mov/?video_id=693134&tmdb=1&audio=tr",
    subUrl: "https://multiembed.mov/?video_id=693134&tmdb=1&sub=Turkish",
  },
  {
    tmdbId: 872585,
    mediaType: "movie",
    title: "Oppenheimer",
    originalTitle: "Oppenheimer",
    overview: "J. Robert Oppenheimer'ın Manhattan Projesi kapsamında ilk nükleer silahları geliştirme sürecini ve ahlaki hesaplaşmalarını anlatan biyografik başyapıt.",
    posterPath: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg",
    releaseYear: "2023",
    voteAverage: 8.1,
    genres: "Dram, Tarih, Biyografi",
    duration: 180,
    videoUrl: "https://player.videasy.net/movie/872585",
    dubUrl: "https://multiembed.mov/?video_id=872585&tmdb=1&audio=tr",
    subUrl: "https://multiembed.mov/?video_id=872585&tmdb=1&sub=Turkish",
  },
  {
    tmdbId: 157336,
    mediaType: "movie",
    title: "Yıldızlararası (Interstellar)",
    originalTitle: "Interstellar",
    overview: "İnsanlığın Dünya'daki ömrü tükenirken bir grup astronot, yeni bir yaşanabilir gezegen bulabilmek için bir solucan deliğinden geçer.",
    posterPath: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
    releaseYear: "2014",
    voteAverage: 8.4,
    genres: "Macera, Dram, Bilim Kurgu",
    duration: 169,
    videoUrl: "https://player.videasy.net/movie/157336",
    dubUrl: "https://multiembed.mov/?video_id=157336&tmdb=1&audio=tr",
    subUrl: "https://multiembed.mov/?video_id=157336&tmdb=1&sub=Turkish",
  },
  {
    tmdbId: 27205,
    mediaType: "movie",
    title: "Başlangıç (Inception)",
    originalTitle: "Inception",
    overview: "Dom Cobb, insanların rüyalarından sırlarını çalan usta bir hırsızdır. Ona sunulan son görev: bir fikri zihne yerleştirmektir.",
    posterPath: "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
    releaseYear: "2010",
    voteAverage: 8.4,
    genres: "Aksiyon, Bilim Kurgu, Macera",
    duration: 148,
    videoUrl: "https://player.videasy.net/movie/27205",
  },
  {
    tmdbId: 155,
    mediaType: "movie",
    title: "Kara Şövalye (The Dark Knight)",
    originalTitle: "The Dark Knight",
    overview: "Batman, Gotham'daki suça karşı mücadeleyi sürdürürken şehri anarşiye sürükleyen Joker ortaya çıkar.",
    posterPath: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/dqK9Hag1054tghRQSqLSfrkvQnA.jpg",
    releaseYear: "2008",
    voteAverage: 8.5,
    genres: "Dram, Aksiyon, Suç, Gerilim",
    duration: 152,
    videoUrl: "https://player.videasy.net/movie/155",
  },
  {
    tmdbId: 550,
    mediaType: "movie",
    title: "Dövüş Kulübü (Fight Club)",
    originalTitle: "Fight Club",
    overview: "Uykusuzluk çeken bir büro çalışanı, Tyler Durden ile tanışır ve hayatı radikal bir dövüş kulübüyle değişir.",
    posterPath: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/hZkgoQYus5vegHoetLkCJzb17zJ.jpg",
    releaseYear: "1999",
    voteAverage: 8.4,
    genres: "Dram, Gerilim",
    duration: 139,
    videoUrl: "https://player.videasy.net/movie/550",
  },
  {
    tmdbId: 603,
    mediaType: "movie",
    title: "Matrix (The Matrix)",
    originalTitle: "The Matrix",
    overview: "Neo, yaşadığı gerçekliğin yapay zeka simülasyonu olduğunu keşfeder ve insanlığı kurtarmak için savaşır.",
    posterPath: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/7u3fh9nfj9q7Tl59jM3f2T0iL.jpg",
    releaseYear: "1999",
    voteAverage: 8.2,
    genres: "Aksiyon, Bilim Kurgu",
    duration: 136,
    videoUrl: "https://player.videasy.net/movie/603",
  },
  {
    tmdbId: 680,
    mediaType: "movie",
    title: "Ucuz Roman (Pulp Fiction)",
    originalTitle: "Pulp Fiction",
    overview: "Los Angeles yeraltı dünyasında iki kiralık katil, bir boksör ve gangsterlerin hayatları birbirine bağlanır.",
    posterPath: "https://image.tmdb.org/t/p/w500/d5iIlFnGhFvlVBs0wV6B1gY0N.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    releaseYear: "1994",
    voteAverage: 8.5,
    genres: "Gerilim, Suç",
    duration: 154,
    videoUrl: "https://player.videasy.net/movie/680",
  },
  {
    tmdbId: 278,
    mediaType: "movie",
    title: "Esaretin Bedeli (The Shawshank Redemption)",
    originalTitle: "The Shawshank Redemption",
    overview: "Haksız yere hapse mahkum edilen Andy Dufresne, Shawshank hapishanesinde umudu canlı tutarak kaçış planı yapar.",
    posterPath: "https://image.tmdb.org/t/p/w500/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
    releaseYear: "1994",
    voteAverage: 8.7,
    genres: "Dram, Suç",
    duration: 142,
    videoUrl: "https://player.videasy.net/movie/278",
  },
  {
    tmdbId: 238,
    mediaType: "movie",
    title: "Baba (The Godfather)",
    originalTitle: "The Godfather",
    overview: "New York mafya ailesi Corleone'lerin lideri Don Vito Corleone ve oğlu Michael'ın suç imparatorluğu hikayesi.",
    posterPath: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/tmU7GeKVybMWF92GImsGZDuAhEj.jpg",
    releaseYear: "1972",
    voteAverage: 8.7,
    genres: "Dram, Suç",
    duration: 175,
    videoUrl: "https://player.videasy.net/movie/238",
  },
  {
    tmdbId: 240,
    mediaType: "movie",
    title: "Baba 2 (The Godfather Part II)",
    originalTitle: "The Godfather Part II",
    overview: "Michael Corleone'nin imparatorluğunu genişletme mücadelesi ve genç Vito Corleone'nin Sicilya'dan Amerika'ya yükselişi.",
    posterPath: "https://image.tmdb.org/t/p/w500/bMadFvyqq2tkqLnjmPOsOiMiMCl.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/kGzFbGhp99zva6vdZ2CpqNDAzdo.jpg",
    releaseYear: "1974",
    voteAverage: 8.6,
    genres: "Dram, Suç",
    duration: 202,
    videoUrl: "https://player.videasy.net/movie/240",
  },
  {
    tmdbId: 120,
    mediaType: "movie",
    title: "Yüzüklerin Efendisi: Yüzük Kardeşliği",
    originalTitle: "The Lord of the Rings: The Fellowship of the Ring",
    overview: "Tek Yüzük'ü yok etmek için Frodo Baggins ve yoldaşları Mordor'a doğru tehlikeli bir yolculuğa çıkar.",
    posterPath: "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/vRQnzOn4H1vt6irSafMMxeJ0TMm.jpg",
    releaseYear: "2001",
    voteAverage: 8.4,
    genres: "Macera, Fantezi, Aksiyon",
    duration: 178,
    videoUrl: "https://player.videasy.net/movie/120",
  },
  {
    tmdbId: 121,
    mediaType: "movie",
    title: "Yüzüklerin Efendisi: İki Kule",
    originalTitle: "The Lord of the Rings: The Two Towers",
    overview: "Yüzük Kardeşliği dağılırken Frodo ve Sam, Gollum eşliğinde Mordor'a yaklaşır; Aragorn ise Rohan halkını savunur.",
    posterPath: "https://image.tmdb.org/t/p/w500/5VTN0pR89TFeJBCcjQvsWfBTuhb.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/kWYfW2Re0rUDE6IHhyvsclcuB9P.jpg",
    releaseYear: "2002",
    voteAverage: 8.4,
    genres: "Macera, Fantezi, Aksiyon",
    duration: 179,
    videoUrl: "https://player.videasy.net/movie/121",
  },
  {
    tmdbId: 122,
    mediaType: "movie",
    title: "Yüzüklerin Efendisi: Kralın Dönüşü",
    originalTitle: "The Lord of the Rings: The Return of the King",
    overview: "Gondor'un kaderini belirleyecek büyük savaş başlarken Frodo ve Sam, Hüküm Dağı'na ulaşır.",
    posterPath: "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg",
    releaseYear: "2003",
    voteAverage: 8.6,
    genres: "Macera, Fantezi, Aksiyon",
    duration: 201,
    videoUrl: "https://player.videasy.net/movie/122",
  },
  {
    tmdbId: 603692,
    mediaType: "movie",
    title: "John Wick: Bölüm 4",
    originalTitle: "John Wick: Chapter 4",
    overview: "John Wick, Yüksek Şura'ya karşı özgürlüğünü kazanmak için dünyanın en güçlü yer altı liderleriyle yüzleşir.",
    posterPath: "https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/h8gHn0OzBoaefW7At1R5JOWTIFG.jpg",
    releaseYear: "2023",
    voteAverage: 7.7,
    genres: "Aksiyon, Gerilim, Suç",
    duration: 169,
    videoUrl: "https://player.videasy.net/movie/603692",
  },
  {
    tmdbId: 414906,
    mediaType: "movie",
    title: "The Batman",
    originalTitle: "The Batman",
    overview: "Gotham Şehri'nin yozlaşmış seçkinlerini hedef alan seri katil Riddler'ın peşine düşen Bruce Wayne'in karanlık hikayesi.",
    posterPath: "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg",
    releaseYear: "2022",
    voteAverage: 7.7,
    genres: "Suç, Gizem, Gerilim",
    duration: 176,
    videoUrl: "https://player.videasy.net/movie/414906",
  },
  {
    tmdbId: 475557,
    mediaType: "movie",
    title: "Joker",
    originalTitle: "Joker",
    overview: "Dışlanan komedyen Arthur Fleck, Gotham'ı kaosa sürükleyen ikonik suç dehasına dönüşür.",
    posterPath: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg",
    releaseYear: "2019",
    voteAverage: 8.2,
    genres: "Suç, Gerilim, Dram",
    duration: 122,
    videoUrl: "https://player.videasy.net/movie/475557",
  },
  {
    tmdbId: 98,
    mediaType: "movie",
    title: "Gladyatör (Gladiator)",
    originalTitle: "Gladiator",
    overview: "İhanete uğrayan General Maximus, intikam almak için Kolezyum'da bir gladyatör olarak yükselir.",
    posterPath: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/Ar7ocvB9v2d1M0U6fO6J1Lq4YkF.jpg",
    releaseYear: "2000",
    voteAverage: 8.2,
    genres: "Aksiyon, Dram, Macera",
    duration: 155,
    videoUrl: "https://player.videasy.net/movie/98",
  },
  {
    tmdbId: 597,
    mediaType: "movie",
    title: "Titanik (Titanic)",
    originalTitle: "Titanic",
    overview: "Tarihin en büyük yolcu gemisinde geçen zengin bir genç kız ile fakir bir ressamın efsanevi aşkı.",
    posterPath: "https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/yDI6D5ZQh67YU4r2ms8YSbvyHQ.jpg",
    releaseYear: "1997",
    voteAverage: 7.9,
    genres: "Dram, Romantik",
    duration: 194,
    videoUrl: "https://player.videasy.net/movie/597",
  },
  {
    tmdbId: 19995,
    mediaType: "movie",
    title: "Avatar",
    originalTitle: "Avatar",
    overview: "Pandora gezegenine gönderilen felçli bir deniz piyadesi, Na'vi halkıyla bağ kurarak gezegeni korumak için savaşır.",
    posterPath: "https://image.tmdb.org/t/p/w500/kyeqWdyUXW608qlYkRqosgbbJyK.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/vL5LR6WdxWPjC3bTf6t67x1yM2x.jpg",
    releaseYear: "2009",
    voteAverage: 7.6,
    genres: "Aksiyon, Macera, Fantezi, Bilim Kurgu",
    duration: 162,
    videoUrl: "https://player.videasy.net/movie/19995",
  },
  {
    tmdbId: 76600,
    mediaType: "movie",
    title: "Avatar: Suyun Yolu",
    originalTitle: "Avatar: The Way of Water",
    overview: "Jake Sully ve Neytiri, Pandora'nın okyanus kabilelerine sığınarak ailelerini korumak için amansız bir mücadeleye girer.",
    posterPath: "https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg",
    releaseYear: "2022",
    voteAverage: 7.7,
    genres: "Bilim Kurgu, Macera, Aksiyon",
    duration: 192,
    videoUrl: "https://player.videasy.net/movie/76600",
  },
  {
    tmdbId: 299534,
    mediaType: "movie",
    title: "Avengers: Endgame",
    originalTitle: "Avengers: Endgame",
    overview: "Thanos'un evreni yarıya indirmesinden sonra kalan Yenilmezler, zaman yolculuğu yaparak her şeyi geri getirmeye çalışır.",
    posterPath: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/7RyHsO4yDXtBv1zJW8Q92Tu0h0x.jpg",
    releaseYear: "2019",
    voteAverage: 8.3,
    genres: "Macera, Bilim Kurgu, Aksiyon",
    duration: 181,
    videoUrl: "https://player.videasy.net/movie/299534",
  },
  {
    tmdbId: 299536,
    mediaType: "movie",
    title: "Avengers: Sonsuzluk Savaşı",
    originalTitle: "Avengers: Infinity War",
    overview: "Yenilmezler ve müttefikleri, evrenin yarısını yok etmek isteyen kudretli Thanos'a karşı tüm güçlerini birleştirir.",
    posterPath: "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/bOGkgRGdhrBYJSLpMumFuRtrCjV.jpg",
    releaseYear: "2018",
    voteAverage: 8.3,
    genres: "Macera, Aksiyon, Bilim Kurgu",
    duration: 149,
    videoUrl: "https://player.videasy.net/movie/299536",
  },
  {
    tmdbId: 634649,
    mediaType: "movie",
    title: "Örümcek-Adam: Eve Dönüş Yok",
    originalTitle: "Spider-Man: No Way Home",
    overview: "Kimliği açığa çıkan Peter Parker, Doctor Strange'den yardım ister; ancak büyü ters giderek çoklu evrenin tehlikeli kötü adamlarını açığa çıkarır.",
    posterPath: "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg",
    releaseYear: "2021",
    voteAverage: 8.0,
    genres: "Aksiyon, Macera, Bilim Kurgu",
    duration: 148,
    videoUrl: "https://player.videasy.net/movie/634649",
  },
  {
    tmdbId: 346698,
    mediaType: "movie",
    title: "Barbie",
    originalTitle: "Barbie",
    overview: "Barbie Diyarı'nda yaşayan bir oyuncak bebek olan Barbie, varoluşsal kriz yaşayarak gerçek dünyaya doğru yolculuğa çıkar.",
    posterPath: "https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/ctMserH8g2SeOAnCw5gFjd2NTL6.jpg",
    releaseYear: "2023",
    voteAverage: 7.2,
    genres: "Komedi, Macera, Fantezi",
    duration: 114,
    videoUrl: "https://player.videasy.net/movie/346698",
  },
  {
    tmdbId: 11,
    mediaType: "movie",
    title: "Yıldız Savaşları: Yeni Bir Umut",
    originalTitle: "Star Wars: Episode IV - A New Hope",
    overview: "Luke Skywalker, Galaktik İmparatorluk'un Ölüm Yıldızı'nı yok etmek için Prenses Leia ve Han Solo ile güçlerini birleştirir.",
    posterPath: "https://image.tmdb.org/t/p/w500/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/zqkmTXzjkAgPnDDXZRs0Ch8Rwqq.jpg",
    releaseYear: "1977",
    voteAverage: 8.2,
    genres: "Macera, Aksiyon, Bilim Kurgu",
    duration: 121,
    videoUrl: "https://player.videasy.net/movie/11",
  },
  {
    tmdbId: 13,
    mediaType: "movie",
    title: "Forrest Gump",
    originalTitle: "Forrest Gump",
    overview: "Düşük IQ'lu ancak sevgi dolu Forrest Gump'ın 20. yüzyıl Amerikan tarihinin dönüm noktalarına dokunan dokunaklı hayatı.",
    posterPath: "https://image.tmdb.org/t/p/w500/arw2VCBveWOVZr6pxd9XTd1TdQa.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/qdIMHdbtatzyIfKcvyuv209MuAh.jpg",
    releaseYear: "1994",
    voteAverage: 8.5,
    genres: "Komedi, Dram, Romantik",
    duration: 142,
    videoUrl: "https://player.videasy.net/movie/13",
  },
  {
    tmdbId: 496243,
    mediaType: "movie",
    title: "Parazit (Parasite)",
    originalTitle: "기생충",
    overview: "Yoksul Kim ailesinin fertleri, kurnazca planlarla zengin Park ailesinin evinde birer birer işe girerek beklenmedik sırlar keşfeder.",
    posterPath: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg",
    releaseYear: "2019",
    voteAverage: 8.5,
    genres: "Komedi, Gerilim, Dram",
    duration: 133,
    videoUrl: "https://player.videasy.net/movie/496243",
  },
  {
    tmdbId: 129,
    mediaType: "movie",
    title: "Ruhların Kaçışı (Spirited Away)",
    originalTitle: "千と千尋の神隠し",
    overview: "Ailesi domuza dönüşen 10 yaşındaki Chihiro, ruhların ve tanrıların yaşadığı gizemli bir hamamda çalışarak onları kurtarmaya çalışır.",
    posterPath: "https://image.tmdb.org/t/p/w500/393rws2e5Vn6hC1Uq2e2eH3qU9V.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/bXNvzjYE9rvBA0LqCuh2eH3qU9V.jpg",
    releaseYear: "2001",
    voteAverage: 8.5,
    genres: "Animasyon, Aile, Fantezi",
    duration: 125,
    videoUrl: "https://player.videasy.net/movie/129",
  },

  // --- TÜRK SİNEMASI KLASİKLERİ VE BAŞYAPITLARI ---
  {
    tmdbId: 9381,
    mediaType: "movie",
    title: "G.O.R.A.",
    originalTitle: "G.O.R.A.",
    overview: "Halı tüccarı Arif, uzaylılar tarafından kaçırılıp G.O.R.A. gezegenine götürülür. Orada prenses Ceku'ya aşık olur ve Komutan Logar'a meydan okur.",
    posterPath: "https://image.tmdb.org/t/p/w500/6yqG2J3Z1D5M6K9H1I3N5Z9M6P.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/9i3N5Z9M6P6yqG2J3Z1D5M6K9H1.jpg",
    releaseYear: "2004",
    voteAverage: 8.0,
    genres: "Komedi, Bilim Kurgu, Macera",
    duration: 127,
    videoUrl: "https://player.videasy.net/movie/9381",
  },
  {
    tmdbId: 21634,
    mediaType: "movie",
    title: "A.R.O.G.",
    originalTitle: "A.R.O.G.",
    overview: "Komutan Logar tarafından taş devrine yollanan Arif, prehistorik insanlara uygarlık öğretirken futbol maçıyla kaderini çizer.",
    posterPath: "https://image.tmdb.org/t/p/w500/6v0m0mQzU9F7r1t9jQ7j0v0.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/6v0m0mQzU9F7r1t9jQ7j0v0.jpg",
    releaseYear: "2008",
    voteAverage: 7.4,
    genres: "Komedi, Bilim Kurgu, Fantezi",
    duration: 129,
    videoUrl: "https://player.videasy.net/movie/21634",
  },
  {
    tmdbId: 10681,
    mediaType: "movie",
    title: "Vizontele",
    originalTitle: "Vizontele",
    overview: "1974 yılında Van'ın küçük bir kasabasına ilk kez televizyon gelir. Belediye Başkanı Nazmi Bey ve kasabanın deli-dahi genci Emin'in hikayesi.",
    posterPath: "https://image.tmdb.org/t/p/w500/y6wG2J3Z1D5M6K9H1I3N5Z9M6P.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/y6wG2J3Z1D5M6K9H1I3N5Z9M6P.jpg",
    releaseYear: "2001",
    voteAverage: 8.0,
    genres: "Komedi, Dram",
    duration: 110,
    videoUrl: "https://player.videasy.net/movie/10681",
  },
  {
    tmdbId: 260346,
    mediaType: "movie",
    title: "Kış Uykusu (Winter Sleep)",
    originalTitle: "Kış Uykusu",
    overview: "Cannes Altın Palmiye ödüllü başyapıt. Emekli tiyatrocu Aydın, Kapadokya'daki otelinde kışın yalnızlığında ahlaki hesaplaşmalar yaşar.",
    posterPath: "https://image.tmdb.org/t/p/w500/qjY7p3M1K0J3r1t9jQ7j0v0.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/qjY7p3M1K0J3r1t9jQ7j0v0.jpg",
    releaseYear: "2014",
    voteAverage: 8.1,
    genres: "Dram",
    duration: 196,
    videoUrl: "https://player.videasy.net/movie/260346",
  },
  {
    tmdbId: 109962,
    mediaType: "movie",
    title: "Bir Zamanlar Anadolu'da",
    originalTitle: "Bir Zamanlar Anadolu'da",
    overview: "Bir savcı, bir doktor ve bir polis amiri, Anadolu bozkırının karanlığında bir ceset aramak için saatler süren felsefi bir yolculuğa çıkar.",
    posterPath: "https://image.tmdb.org/t/p/w500/a9K0J3r1t9jQ7j0v0m0mQzU9F7r.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/a9K0J3r1t9jQ7j0v0m0mQzU9F7r.jpg",
    releaseYear: "2011",
    voteAverage: 7.9,
    genres: "Dram, Suç",
    duration: 157,
    videoUrl: "https://player.videasy.net/movie/109962",
  },
  {
    tmdbId: 35147,
    mediaType: "movie",
    title: "Babam ve Oğlum",
    originalTitle: "Babam ve Oğlum",
    overview: "12 Eylül darbesinin gölgesinde büyüyen bir çocuk ve küs olduğu babasının yanına dönen bir gazetecinin yürek burkan dramı.",
    posterPath: "https://image.tmdb.org/t/p/w500/u3K0J3r1t9jQ7j0v0m0mQzU9F7r.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/u3K0J3r1t9jQ7j0v0m0mQzU9F7r.jpg",
    releaseYear: "2005",
    voteAverage: 8.3,
    genres: "Dram, Aile",
    duration: 108,
    videoUrl: "https://player.videasy.net/movie/35147",
  },
  {
    tmdbId: 44214,
    mediaType: "movie",
    title: "Eşkıya",
    originalTitle: "Eşkıya",
    overview: "35 yıl hapis yatan Baran, sevdiği kadını ve kendisine ihanet eden arkadaşını bulmak için İstanbul'un acımasız sokaklarına gelir.",
    posterPath: "https://image.tmdb.org/t/p/w500/v4K0J3r1t9jQ7j0v0m0mQzU9F7r.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/v4K0J3r1t9jQ7j0v0m0mQzU9F7r.jpg",
    releaseYear: "1996",
    voteAverage: 8.1,
    genres: "Dram, Suç, Aksiyon",
    duration: 128,
    videoUrl: "https://player.videasy.net/movie/44214",
  },
  {
    tmdbId: 10193,
    mediaType: "movie",
    title: "Hababam Sınıfı",
    originalTitle: "Hababam Sınıfı",
    overview: "Özel Çamlıca Lisesi'nin haylaz ve eğlenceli sınıfı Hababam Sınıfı ile disiplinli Müdür Muavini Mahmut Hoca'nın unutulmaz mücadelesi.",
    posterPath: "https://image.tmdb.org/t/p/w500/w5K0J3r1t9jQ7j0v0m0mQzU9F7r.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/w5K0J3r1t9jQ7j0v0m0mQzU9F7r.jpg",
    releaseYear: "1975",
    voteAverage: 8.6,
    genres: "Komedi, Klasik",
    duration: 87,
    videoUrl: "https://player.videasy.net/movie/10193",
  },
  {
    tmdbId: 10194,
    mediaType: "movie",
    title: "Tosun Paşa",
    originalTitle: "Tosun Paşa",
    overview: "Tellioğulları ve Seferoğulları aileleri arasındaki Yeşil Vadi mücadelesinde uşak Şaban, İskenderiye'nin en kudretli paşası Tosun Paşa kılığına girer.",
    posterPath: "https://image.tmdb.org/t/p/w500/x6K0J3r1t9jQ7j0v0m0mQzU9F7r.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/x6K0J3r1t9jQ7j0v0m0mQzU9F7r.jpg",
    releaseYear: "1976",
    voteAverage: 8.4,
    genres: "Komedi, Tarih",
    duration: 90,
    videoUrl: "https://player.videasy.net/movie/10194",
  },

  // --- POPÜLER VE EFSANEVİ DİZİLER ---
  {
    tmdbId: 1396,
    mediaType: "tv",
    title: "Breaking Bad",
    originalTitle: "Breaking Bad",
    overview: "Kanser teşhisi konan bir lise kimya öğretmeni olan Walter White, ailesinin geleceğini garanti altına almak için metamfetamin üretimine başlar.",
    posterPath: "https://image.tmdb.org/t/p/w500/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg",
    releaseYear: "2008",
    voteAverage: 8.9,
    genres: "Dram, Suç",
    seasonsCount: 5,
    episodesCount: 62,
    isFeatured: true,
    videoUrl: "https://player.videasy.net/tv/1396/1/1",
    dubUrl: "https://multiembed.mov/?video_id=1396&tmdb=1&s=1&e=1&audio=tr",
    subUrl: "https://multiembed.mov/?video_id=1396&tmdb=1&s=1&e=1&sub=Turkish",
  },
  {
    tmdbId: 94605,
    mediaType: "tv",
    title: "Arcane",
    originalTitle: "Arcane",
    overview: "Piltover'ın ütopik şehri ile Zaun'un yeraltı dünyası arasındaki çatışmada Vi ve Jinx karşı karşıya gelir.",
    posterPath: "https://image.tmdb.org/t/p/w500/fqldf2t8ztc9aiwn397rHgYeRao.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/2ombOoJYJUmnvdLz4n0zM572s6y.jpg",
    releaseYear: "2021",
    voteAverage: 8.7,
    genres: "Animasyon, Bilim Kurgu, Aksiyon",
    seasonsCount: 2,
    episodesCount: 18,
    videoUrl: "https://player.videasy.net/tv/94605/1/1",
  },
  {
    tmdbId: 66732,
    mediaType: "tv",
    title: "Stranger Things",
    originalTitle: "Stranger Things",
    overview: "Küçük bir kasabada bir çocuğun kaybolmasıyla başlayan gizemli ve doğaüstü olaylar.",
    posterPath: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
    releaseYear: "2016",
    voteAverage: 8.6,
    genres: "Bilim Kurgu, Dram, Gizem",
    seasonsCount: 4,
    episodesCount: 34,
    videoUrl: "https://player.videasy.net/tv/66732/1/1",
  },
  {
    tmdbId: 1399,
    mediaType: "tv",
    title: "Taht Oyunları (Game of Thrones)",
    originalTitle: "Game of Thrones",
    overview: "Westeros'un Demir Taht'ı ele geçirmek için soylu hanedanların amansız mücadelesi.",
    posterPath: "https://image.tmdb.org/t/p/w500/7WUhnWGx5OOt4ljR0ZmBg3Q0ngn.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg",
    releaseYear: "2011",
    voteAverage: 8.4,
    genres: "Dram, Fantezi, Macera",
    seasonsCount: 8,
    episodesCount: 73,
    videoUrl: "https://player.videasy.net/tv/1399/1/1",
  },
  {
    tmdbId: 100088,
    mediaType: "tv",
    title: "The Last of Us",
    originalTitle: "The Last of Us",
    overview: "Salgın sonrası dünyada Joel ve Ellie'nin hayatta kalma mücadelesi.",
    posterPath: "https://image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqAt2V7JMrRI.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg",
    releaseYear: "2023",
    voteAverage: 8.6,
    genres: "Dram, Macera, Bilim Kurgu",
    seasonsCount: 1,
    episodesCount: 9,
    videoUrl: "https://player.videasy.net/tv/100088/1/1",
  },
  {
    tmdbId: 76479,
    mediaType: "tv",
    title: "The Boys",
    originalTitle: "The Boys",
    overview: "Yozlaşmış süper kahramanlara karşı savaşan sıradan insanların acımasız mücadelesi.",
    posterPath: "https://image.tmdb.org/t/p/w500/7Ns6tO3aYjppI5LoNOi397SC347.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg",
    releaseYear: "2019",
    voteAverage: 8.5,
    genres: "Bilim Kurgu, Aksiyon, Komedi",
    seasonsCount: 4,
    episodesCount: 32,
    videoUrl: "https://player.videasy.net/tv/76479/1/1",
  },
  {
    tmdbId: 60059,
    mediaType: "tv",
    title: "Better Call Saul",
    originalTitle: "Better Call Saul",
    overview: "Jimmy McGill'in kurnaz suç avukatı Saul Goodman'a dönüşüm serüveni.",
    posterPath: "https://image.tmdb.org/t/p/w500/fC2HDm5t0kHsf79dSZQH7QCJDCv.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/r0Q6vd9AyHJ5YQG48T6Eg93WPaE.jpg",
    releaseYear: "2015",
    voteAverage: 8.7,
    genres: "Dram, Suç",
    seasonsCount: 6,
    episodesCount: 63,
    videoUrl: "https://player.videasy.net/tv/60059/1/1",
  },
  {
    tmdbId: 87108,
    mediaType: "tv",
    title: "Chernobyl",
    originalTitle: "Chernobyl",
    overview: "Çernobil Nükleer Santrali patlamasının perde arkasını anlatan başyapıt mini dizi.",
    posterPath: "https://image.tmdb.org/t/p/w500/hlLXt2tOPT6RRnjiUmoxyG9LTFi.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/uL6Ad12W0m6v2d1rPzT9c1T7v0f.jpg",
    releaseYear: "2019",
    voteAverage: 8.7,
    genres: "Dram, Tarih",
    seasonsCount: 1,
    episodesCount: 5,
    videoUrl: "https://player.videasy.net/tv/87108/1/1",
  },
  {
    tmdbId: 30983,
    mediaType: "tv",
    title: "Ezel",
    originalTitle: "Ezel",
    overview: "Dostlarının ihanetine uğrayan Ömer'in intikam almak için Ezel olarak geri dönüşü.",
    posterPath: "https://image.tmdb.org/t/p/w500/jL5M6K9H1I3N5Z9M6P6yqG2J3Z1.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/jL5M6K9H1I3N5Z9M6P6yqG2J3Z1.jpg",
    releaseYear: "2009",
    voteAverage: 8.8,
    genres: "Dram, Suç, Aksiyon",
    seasonsCount: 2,
    episodesCount: 71,
    isFeatured: true,
    videoUrl: "https://player.videasy.net/tv/30983/1/1",
  },
  {
    tmdbId: 44264,
    mediaType: "tv",
    title: "Behzat Ç. Bir Ankara Polisiyesi",
    originalTitle: "Behzat Ç.",
    overview: "Cinayet Büro Amiri Behzat Ç. ve ekibinin başkentin karanlık cinayetlerini çözme mücadelesi.",
    posterPath: "https://image.tmdb.org/t/p/w500/kK9H1I3N5Z9M6P6yqG2J3Z1D5M6.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/kK9H1I3N5Z9M6P6yqG2J3Z1D5M6.jpg",
    releaseYear: "2010",
    voteAverage: 8.7,
    genres: "Dram, Suç, Gizem",
    seasonsCount: 4,
    episodesCount: 105,
    videoUrl: "https://player.videasy.net/tv/44264/1/1",
  },
  {
    tmdbId: 119864,
    mediaType: "tv",
    title: "Gibi",
    originalTitle: "Gibi",
    overview: "Yılmaz, İlkkan ve Ersoy'un sıradan görünen hayatlarındaki absürt ve trajikomik maceralar.",
    posterPath: "https://image.tmdb.org/t/p/w500/mI3N5Z9M6P6yqG2J3Z1D5M6K9H1.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/mI3N5Z9M6P6yqG2J3Z1D5M6K9H1.jpg",
    releaseYear: "2021",
    voteAverage: 8.9,
    genres: "Komedi",
    seasonsCount: 5,
    episodesCount: 55,
    videoUrl: "https://player.videasy.net/tv/119864/1/1",
  },
  {
    tmdbId: 94997,
    mediaType: "tv",
    title: "Kurtlar Vadisi",
    originalTitle: "Kurtlar Vadisi",
    overview: "Ali Candan'ın yüzünü ve kimliğini değiştirerek Polat Alemdar adıyla mafyanın içine sızıp baronlar konseyini çökertme serüveni.",
    posterPath: "https://image.tmdb.org/t/p/w500/u1K0J3r1t9jQ7j0v0m0mQzU9F7r.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/u1K0J3r1t9jQ7j0v0m0mQzU9F7r.jpg",
    releaseYear: "2003",
    voteAverage: 8.9,
    genres: "Aksiyon, Suç, Dram",
    seasonsCount: 4,
    episodesCount: 97,
    videoUrl: "https://player.videasy.net/tv/94997/1/1",
  },
  {
    tmdbId: 19885,
    mediaType: "tv",
    title: "Sherlock",
    originalTitle: "Sherlock",
    overview: "Modern Londra'da dahi dedektif Sherlock Holmes ve ortağı Dr. John Watson'ın karmaşık gizemleri çözüşü.",
    posterPath: "https://image.tmdb.org/t/p/w500/7WTsnDMmstAwh9cf9R19sO2MmNW.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/s265mU6z07kXjJ7Y526o19sO2Mm.jpg",
    releaseYear: "2010",
    voteAverage: 8.5,
    genres: "Suç, Dram, Gizem",
    seasonsCount: 4,
    episodesCount: 15,
    videoUrl: "https://player.videasy.net/tv/19885/1/1",
  },
  {
    tmdbId: 60625,
    mediaType: "tv",
    title: "Rick ve Morty (Rick and Morty)",
    originalTitle: "Rick and Morty",
    overview: "Dahi ve alkolik dede Rick ile torunu Morty'nin çoklu evrenlerde yaşadığı çılgın ve tehlikeli bilim kurgu maceraları.",
    posterPath: "https://image.tmdb.org/t/p/w500/cvhNj9eoRBe5SxjardQTyz0a4Ka.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/uLtVbvOEkemMVbuuk47ZE3vFncS.jpg",
    releaseYear: "2013",
    voteAverage: 8.7,
    genres: "Animasyon, Komedi, Bilim Kurgu",
    seasonsCount: 7,
    episodesCount: 71,
    videoUrl: "https://player.videasy.net/tv/60625/1/1",
  },
];

async function main() {
  console.log("Geniş film ve dizi arşivi veritabanına aktarılıyor...");

  let added = 0;
  for (const item of LARGE_LIBRARY) {
    await prisma.mediaItem.upsert({
      where: { tmdbId: item.tmdbId },
      update: item,
      create: item,
    });
    added++;
  }

  console.log(`Tamamlandı! Toplam ${added} adet film ve dizi başarıyla yerel veritabanına kaydedildi.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
